name: react-frontend-demo
recipe: lemp
services:
  appserver:
    app_mount: false
    xdebug: debug, develop
    config:
      php: .lando/php.ini
    build_as_root:
      - cd /react-frontend-demo/.lando/ && ./setup-wordpress-files.sh && ./install-wp-cli.sh
    run:
      - /react-frontend-demo/.lando/install-wordpress.sh
    overrides:
      volumes:
        - .:/react-frontend-demo
      environment:
        WP_CLI_CONFIG_PATH: /wordpress/wp-cli.yml
  appserver_nginx:
    build_as_root:
      - /react-frontend-demo/.lando/setup-wordpress-files.sh
config:
  php: '8.2'
  config:  
    vhosts: .lando/nginx.conf
tooling:
  wp:
    service: appserver
    description: Runs WP-CLI commands
    cmd: wp
